# Generated by Django 4.0.4 on 2022-04-21 07:04

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField(max_length=1000)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2022, 4, 21, 7, 4, 54, 472288, tzinfo=utc))),
            ],
        ),
    ]
